---
http_interactions:
- request:
    method: get
    uri: https://hawkular.example.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer the_token
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '133'
      Date:
      - Wed, 26 Oct 2016 08:24:58 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=408987ff52f5c660d744129185bb9e8b; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.18.3.Final","Built-From-Git-SHA1":"38ea6c2a1e33ed1024684084812ad2ad5730fb76"}'
    http_version: 
  recorded_at: Wed, 26 Oct 2016 08:24:58 GMT
- request:
    method: get
    uri: https://hawkular.example.com/hawkular/metrics/availability/all/raw/?limit=1
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.2.4p230
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer the_token
      Content-Type:
      - application/json
  response:
    status:
      code: 204
      message: No Content
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Date:
      - Wed, 26 Oct 2016 08:24:59 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=408987ff52f5c660d744129185bb9e8b; path=/;
        HttpOnly; Secure
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Wed, 26 Oct 2016 08:24:59 GMT
recorded_with: VCR 3.0.3
